FROM golang:1.23-bullseye AS base

ENV GOCACHE=/go/.go/cache GOPATH=/go/.go/path TZ=Europe/London

RUN GOBIN=/bin go install github.com/cespare/reflex@v0.3.1

RUN echo "pwd: $(pwd)"

# Map between the working directories of dev and live
RUN ln -s /go /dp-filter-api
WORKDIR /dp-filter-api
