// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-filter-api/models"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/globalsign/mgo/bson"
	"sync"
)

var (
	lockMongoDBMockAddEventToFilterOutput       sync.RWMutex
	lockMongoDBMockAddFilter                    sync.RWMutex
	lockMongoDBMockAddFilterDimension           sync.RWMutex
	lockMongoDBMockAddFilterDimensionOption     sync.RWMutex
	lockMongoDBMockAddFilterDimensionOptions    sync.RWMutex
	lockMongoDBMockChecker                      sync.RWMutex
	lockMongoDBMockClose                        sync.RWMutex
	lockMongoDBMockCreateFilterOutput           sync.RWMutex
	lockMongoDBMockGetFilter                    sync.RWMutex
	lockMongoDBMockGetFilterDimension           sync.RWMutex
	lockMongoDBMockGetFilterOutput              sync.RWMutex
	lockMongoDBMockRemoveFilterDimension        sync.RWMutex
	lockMongoDBMockRemoveFilterDimensionOption  sync.RWMutex
	lockMongoDBMockRemoveFilterDimensionOptions sync.RWMutex
	lockMongoDBMockUpdateFilter                 sync.RWMutex
	lockMongoDBMockUpdateFilterOutput           sync.RWMutex
)

// MongoDBMock is a mock implementation of service.MongoDB.
//
//     func TestSomethingThatUsesMongoDB(t *testing.T) {
//
//         // make and configure a mocked service.MongoDB
//         mockedMongoDB := &MongoDBMock{
//             AddEventToFilterOutputFunc: func(filterOutputID string, event *models.Event) error {
// 	               panic("mock out the AddEventToFilterOutput method")
//             },
//             AddFilterFunc: func(filter *models.Filter) (*models.Filter, error) {
// 	               panic("mock out the AddFilter method")
//             },
//             AddFilterDimensionFunc: func(filterID string, name string, options []string, dimensions []models.Dimension, timestamp bson.MongoTimestamp) error {
// 	               panic("mock out the AddFilterDimension method")
//             },
//             AddFilterDimensionOptionFunc: func(filterID string, name string, option string, timestamp bson.MongoTimestamp) error {
// 	               panic("mock out the AddFilterDimensionOption method")
//             },
//             AddFilterDimensionOptionsFunc: func(filterID string, name string, options []string, timestamp bson.MongoTimestamp) error {
// 	               panic("mock out the AddFilterDimensionOptions method")
//             },
//             CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//             CloseFunc: func(ctx context.Context) error {
// 	               panic("mock out the Close method")
//             },
//             CreateFilterOutputFunc: func(filter *models.Filter) error {
// 	               panic("mock out the CreateFilterOutput method")
//             },
//             GetFilterFunc: func(filterID string) (*models.Filter, error) {
// 	               panic("mock out the GetFilter method")
//             },
//             GetFilterDimensionFunc: func(filterID string, name string) (*models.Dimension, error) {
// 	               panic("mock out the GetFilterDimension method")
//             },
//             GetFilterOutputFunc: func(filterOutputID string) (*models.Filter, error) {
// 	               panic("mock out the GetFilterOutput method")
//             },
//             RemoveFilterDimensionFunc: func(filterID string, name string, timestamp bson.MongoTimestamp) error {
// 	               panic("mock out the RemoveFilterDimension method")
//             },
//             RemoveFilterDimensionOptionFunc: func(filterID string, name string, option string, timestamp bson.MongoTimestamp) error {
// 	               panic("mock out the RemoveFilterDimensionOption method")
//             },
//             RemoveFilterDimensionOptionsFunc: func(filterID string, name string, options []string, timestamp bson.MongoTimestamp) error {
// 	               panic("mock out the RemoveFilterDimensionOptions method")
//             },
//             UpdateFilterFunc: func(filter *models.Filter, timestamp bson.MongoTimestamp) error {
// 	               panic("mock out the UpdateFilter method")
//             },
//             UpdateFilterOutputFunc: func(filterOutput *models.Filter, timestamp bson.MongoTimestamp) error {
// 	               panic("mock out the UpdateFilterOutput method")
//             },
//         }
//
//         // use mockedMongoDB in code that requires service.MongoDB
//         // and then make assertions.
//
//     }
type MongoDBMock struct {
	// AddEventToFilterOutputFunc mocks the AddEventToFilterOutput method.
	AddEventToFilterOutputFunc func(filterOutputID string, event *models.Event) error

	// AddFilterFunc mocks the AddFilter method.
	AddFilterFunc func(filter *models.Filter) (*models.Filter, error)

	// AddFilterDimensionFunc mocks the AddFilterDimension method.
	AddFilterDimensionFunc func(filterID string, name string, options []string, dimensions []models.Dimension, timestamp bson.MongoTimestamp) error

	// AddFilterDimensionOptionFunc mocks the AddFilterDimensionOption method.
	AddFilterDimensionOptionFunc func(filterID string, name string, option string, timestamp bson.MongoTimestamp) error

	// AddFilterDimensionOptionsFunc mocks the AddFilterDimensionOptions method.
	AddFilterDimensionOptionsFunc func(filterID string, name string, options []string, timestamp bson.MongoTimestamp) error

	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context) error

	// CreateFilterOutputFunc mocks the CreateFilterOutput method.
	CreateFilterOutputFunc func(filter *models.Filter) error

	// GetFilterFunc mocks the GetFilter method.
	GetFilterFunc func(filterID string) (*models.Filter, error)

	// GetFilterDimensionFunc mocks the GetFilterDimension method.
	GetFilterDimensionFunc func(filterID string, name string) (*models.Dimension, error)

	// GetFilterOutputFunc mocks the GetFilterOutput method.
	GetFilterOutputFunc func(filterOutputID string) (*models.Filter, error)

	// RemoveFilterDimensionFunc mocks the RemoveFilterDimension method.
	RemoveFilterDimensionFunc func(filterID string, name string, timestamp bson.MongoTimestamp) error

	// RemoveFilterDimensionOptionFunc mocks the RemoveFilterDimensionOption method.
	RemoveFilterDimensionOptionFunc func(filterID string, name string, option string, timestamp bson.MongoTimestamp) error

	// RemoveFilterDimensionOptionsFunc mocks the RemoveFilterDimensionOptions method.
	RemoveFilterDimensionOptionsFunc func(filterID string, name string, options []string, timestamp bson.MongoTimestamp) error

	// UpdateFilterFunc mocks the UpdateFilter method.
	UpdateFilterFunc func(filter *models.Filter, timestamp bson.MongoTimestamp) error

	// UpdateFilterOutputFunc mocks the UpdateFilterOutput method.
	UpdateFilterOutputFunc func(filterOutput *models.Filter, timestamp bson.MongoTimestamp) error

	// calls tracks calls to the methods.
	calls struct {
		// AddEventToFilterOutput holds details about calls to the AddEventToFilterOutput method.
		AddEventToFilterOutput []struct {
			// FilterOutputID is the filterOutputID argument value.
			FilterOutputID string
			// Event is the event argument value.
			Event *models.Event
		}
		// AddFilter holds details about calls to the AddFilter method.
		AddFilter []struct {
			// Filter is the filter argument value.
			Filter *models.Filter
		}
		// AddFilterDimension holds details about calls to the AddFilterDimension method.
		AddFilterDimension []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []string
			// Dimensions is the dimensions argument value.
			Dimensions []models.Dimension
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// AddFilterDimensionOption holds details about calls to the AddFilterDimensionOption method.
		AddFilterDimensionOption []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Option is the option argument value.
			Option string
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// AddFilterDimensionOptions holds details about calls to the AddFilterDimensionOptions method.
		AddFilterDimensionOptions []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []string
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateFilterOutput holds details about calls to the CreateFilterOutput method.
		CreateFilterOutput []struct {
			// Filter is the filter argument value.
			Filter *models.Filter
		}
		// GetFilter holds details about calls to the GetFilter method.
		GetFilter []struct {
			// FilterID is the filterID argument value.
			FilterID string
		}
		// GetFilterDimension holds details about calls to the GetFilterDimension method.
		GetFilterDimension []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
		}
		// GetFilterOutput holds details about calls to the GetFilterOutput method.
		GetFilterOutput []struct {
			// FilterOutputID is the filterOutputID argument value.
			FilterOutputID string
		}
		// RemoveFilterDimension holds details about calls to the RemoveFilterDimension method.
		RemoveFilterDimension []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// RemoveFilterDimensionOption holds details about calls to the RemoveFilterDimensionOption method.
		RemoveFilterDimensionOption []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Option is the option argument value.
			Option string
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// RemoveFilterDimensionOptions holds details about calls to the RemoveFilterDimensionOptions method.
		RemoveFilterDimensionOptions []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []string
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// UpdateFilter holds details about calls to the UpdateFilter method.
		UpdateFilter []struct {
			// Filter is the filter argument value.
			Filter *models.Filter
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// UpdateFilterOutput holds details about calls to the UpdateFilterOutput method.
		UpdateFilterOutput []struct {
			// FilterOutput is the filterOutput argument value.
			FilterOutput *models.Filter
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
	}
}

// AddEventToFilterOutput calls AddEventToFilterOutputFunc.
func (mock *MongoDBMock) AddEventToFilterOutput(filterOutputID string, event *models.Event) error {
	if mock.AddEventToFilterOutputFunc == nil {
		panic("MongoDBMock.AddEventToFilterOutputFunc: method is nil but MongoDB.AddEventToFilterOutput was just called")
	}
	callInfo := struct {
		FilterOutputID string
		Event          *models.Event
	}{
		FilterOutputID: filterOutputID,
		Event:          event,
	}
	lockMongoDBMockAddEventToFilterOutput.Lock()
	mock.calls.AddEventToFilterOutput = append(mock.calls.AddEventToFilterOutput, callInfo)
	lockMongoDBMockAddEventToFilterOutput.Unlock()
	return mock.AddEventToFilterOutputFunc(filterOutputID, event)
}

// AddEventToFilterOutputCalls gets all the calls that were made to AddEventToFilterOutput.
// Check the length with:
//     len(mockedMongoDB.AddEventToFilterOutputCalls())
func (mock *MongoDBMock) AddEventToFilterOutputCalls() []struct {
	FilterOutputID string
	Event          *models.Event
} {
	var calls []struct {
		FilterOutputID string
		Event          *models.Event
	}
	lockMongoDBMockAddEventToFilterOutput.RLock()
	calls = mock.calls.AddEventToFilterOutput
	lockMongoDBMockAddEventToFilterOutput.RUnlock()
	return calls
}

// AddFilter calls AddFilterFunc.
func (mock *MongoDBMock) AddFilter(filter *models.Filter) (*models.Filter, error) {
	if mock.AddFilterFunc == nil {
		panic("MongoDBMock.AddFilterFunc: method is nil but MongoDB.AddFilter was just called")
	}
	callInfo := struct {
		Filter *models.Filter
	}{
		Filter: filter,
	}
	lockMongoDBMockAddFilter.Lock()
	mock.calls.AddFilter = append(mock.calls.AddFilter, callInfo)
	lockMongoDBMockAddFilter.Unlock()
	return mock.AddFilterFunc(filter)
}

// AddFilterCalls gets all the calls that were made to AddFilter.
// Check the length with:
//     len(mockedMongoDB.AddFilterCalls())
func (mock *MongoDBMock) AddFilterCalls() []struct {
	Filter *models.Filter
} {
	var calls []struct {
		Filter *models.Filter
	}
	lockMongoDBMockAddFilter.RLock()
	calls = mock.calls.AddFilter
	lockMongoDBMockAddFilter.RUnlock()
	return calls
}

// AddFilterDimension calls AddFilterDimensionFunc.
func (mock *MongoDBMock) AddFilterDimension(filterID string, name string, options []string, dimensions []models.Dimension, timestamp bson.MongoTimestamp) error {
	if mock.AddFilterDimensionFunc == nil {
		panic("MongoDBMock.AddFilterDimensionFunc: method is nil but MongoDB.AddFilterDimension was just called")
	}
	callInfo := struct {
		FilterID   string
		Name       string
		Options    []string
		Dimensions []models.Dimension
		Timestamp  bson.MongoTimestamp
	}{
		FilterID:   filterID,
		Name:       name,
		Options:    options,
		Dimensions: dimensions,
		Timestamp:  timestamp,
	}
	lockMongoDBMockAddFilterDimension.Lock()
	mock.calls.AddFilterDimension = append(mock.calls.AddFilterDimension, callInfo)
	lockMongoDBMockAddFilterDimension.Unlock()
	return mock.AddFilterDimensionFunc(filterID, name, options, dimensions, timestamp)
}

// AddFilterDimensionCalls gets all the calls that were made to AddFilterDimension.
// Check the length with:
//     len(mockedMongoDB.AddFilterDimensionCalls())
func (mock *MongoDBMock) AddFilterDimensionCalls() []struct {
	FilterID   string
	Name       string
	Options    []string
	Dimensions []models.Dimension
	Timestamp  bson.MongoTimestamp
} {
	var calls []struct {
		FilterID   string
		Name       string
		Options    []string
		Dimensions []models.Dimension
		Timestamp  bson.MongoTimestamp
	}
	lockMongoDBMockAddFilterDimension.RLock()
	calls = mock.calls.AddFilterDimension
	lockMongoDBMockAddFilterDimension.RUnlock()
	return calls
}

// AddFilterDimensionOption calls AddFilterDimensionOptionFunc.
func (mock *MongoDBMock) AddFilterDimensionOption(filterID string, name string, option string, timestamp bson.MongoTimestamp) error {
	if mock.AddFilterDimensionOptionFunc == nil {
		panic("MongoDBMock.AddFilterDimensionOptionFunc: method is nil but MongoDB.AddFilterDimensionOption was just called")
	}
	callInfo := struct {
		FilterID  string
		Name      string
		Option    string
		Timestamp bson.MongoTimestamp
	}{
		FilterID:  filterID,
		Name:      name,
		Option:    option,
		Timestamp: timestamp,
	}
	lockMongoDBMockAddFilterDimensionOption.Lock()
	mock.calls.AddFilterDimensionOption = append(mock.calls.AddFilterDimensionOption, callInfo)
	lockMongoDBMockAddFilterDimensionOption.Unlock()
	return mock.AddFilterDimensionOptionFunc(filterID, name, option, timestamp)
}

// AddFilterDimensionOptionCalls gets all the calls that were made to AddFilterDimensionOption.
// Check the length with:
//     len(mockedMongoDB.AddFilterDimensionOptionCalls())
func (mock *MongoDBMock) AddFilterDimensionOptionCalls() []struct {
	FilterID  string
	Name      string
	Option    string
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		FilterID  string
		Name      string
		Option    string
		Timestamp bson.MongoTimestamp
	}
	lockMongoDBMockAddFilterDimensionOption.RLock()
	calls = mock.calls.AddFilterDimensionOption
	lockMongoDBMockAddFilterDimensionOption.RUnlock()
	return calls
}

// AddFilterDimensionOptions calls AddFilterDimensionOptionsFunc.
func (mock *MongoDBMock) AddFilterDimensionOptions(filterID string, name string, options []string, timestamp bson.MongoTimestamp) error {
	if mock.AddFilterDimensionOptionsFunc == nil {
		panic("MongoDBMock.AddFilterDimensionOptionsFunc: method is nil but MongoDB.AddFilterDimensionOptions was just called")
	}
	callInfo := struct {
		FilterID  string
		Name      string
		Options   []string
		Timestamp bson.MongoTimestamp
	}{
		FilterID:  filterID,
		Name:      name,
		Options:   options,
		Timestamp: timestamp,
	}
	lockMongoDBMockAddFilterDimensionOptions.Lock()
	mock.calls.AddFilterDimensionOptions = append(mock.calls.AddFilterDimensionOptions, callInfo)
	lockMongoDBMockAddFilterDimensionOptions.Unlock()
	return mock.AddFilterDimensionOptionsFunc(filterID, name, options, timestamp)
}

// AddFilterDimensionOptionsCalls gets all the calls that were made to AddFilterDimensionOptions.
// Check the length with:
//     len(mockedMongoDB.AddFilterDimensionOptionsCalls())
func (mock *MongoDBMock) AddFilterDimensionOptionsCalls() []struct {
	FilterID  string
	Name      string
	Options   []string
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		FilterID  string
		Name      string
		Options   []string
		Timestamp bson.MongoTimestamp
	}
	lockMongoDBMockAddFilterDimensionOptions.RLock()
	calls = mock.calls.AddFilterDimensionOptions
	lockMongoDBMockAddFilterDimensionOptions.RUnlock()
	return calls
}

// Checker calls CheckerFunc.
func (mock *MongoDBMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("MongoDBMock.CheckerFunc: method is nil but MongoDB.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	lockMongoDBMockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	lockMongoDBMockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedMongoDB.CheckerCalls())
func (mock *MongoDBMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	lockMongoDBMockChecker.RLock()
	calls = mock.calls.Checker
	lockMongoDBMockChecker.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *MongoDBMock) Close(ctx context.Context) error {
	if mock.CloseFunc == nil {
		panic("MongoDBMock.CloseFunc: method is nil but MongoDB.Close was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockMongoDBMockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	lockMongoDBMockClose.Unlock()
	return mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedMongoDB.CloseCalls())
func (mock *MongoDBMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockMongoDBMockClose.RLock()
	calls = mock.calls.Close
	lockMongoDBMockClose.RUnlock()
	return calls
}

// CreateFilterOutput calls CreateFilterOutputFunc.
func (mock *MongoDBMock) CreateFilterOutput(filter *models.Filter) error {
	if mock.CreateFilterOutputFunc == nil {
		panic("MongoDBMock.CreateFilterOutputFunc: method is nil but MongoDB.CreateFilterOutput was just called")
	}
	callInfo := struct {
		Filter *models.Filter
	}{
		Filter: filter,
	}
	lockMongoDBMockCreateFilterOutput.Lock()
	mock.calls.CreateFilterOutput = append(mock.calls.CreateFilterOutput, callInfo)
	lockMongoDBMockCreateFilterOutput.Unlock()
	return mock.CreateFilterOutputFunc(filter)
}

// CreateFilterOutputCalls gets all the calls that were made to CreateFilterOutput.
// Check the length with:
//     len(mockedMongoDB.CreateFilterOutputCalls())
func (mock *MongoDBMock) CreateFilterOutputCalls() []struct {
	Filter *models.Filter
} {
	var calls []struct {
		Filter *models.Filter
	}
	lockMongoDBMockCreateFilterOutput.RLock()
	calls = mock.calls.CreateFilterOutput
	lockMongoDBMockCreateFilterOutput.RUnlock()
	return calls
}

// GetFilter calls GetFilterFunc.
func (mock *MongoDBMock) GetFilter(filterID string) (*models.Filter, error) {
	if mock.GetFilterFunc == nil {
		panic("MongoDBMock.GetFilterFunc: method is nil but MongoDB.GetFilter was just called")
	}
	callInfo := struct {
		FilterID string
	}{
		FilterID: filterID,
	}
	lockMongoDBMockGetFilter.Lock()
	mock.calls.GetFilter = append(mock.calls.GetFilter, callInfo)
	lockMongoDBMockGetFilter.Unlock()
	return mock.GetFilterFunc(filterID)
}

// GetFilterCalls gets all the calls that were made to GetFilter.
// Check the length with:
//     len(mockedMongoDB.GetFilterCalls())
func (mock *MongoDBMock) GetFilterCalls() []struct {
	FilterID string
} {
	var calls []struct {
		FilterID string
	}
	lockMongoDBMockGetFilter.RLock()
	calls = mock.calls.GetFilter
	lockMongoDBMockGetFilter.RUnlock()
	return calls
}

// GetFilterDimension calls GetFilterDimensionFunc.
func (mock *MongoDBMock) GetFilterDimension(filterID string, name string) (*models.Dimension, error) {
	if mock.GetFilterDimensionFunc == nil {
		panic("MongoDBMock.GetFilterDimensionFunc: method is nil but MongoDB.GetFilterDimension was just called")
	}
	callInfo := struct {
		FilterID string
		Name     string
	}{
		FilterID: filterID,
		Name:     name,
	}
	lockMongoDBMockGetFilterDimension.Lock()
	mock.calls.GetFilterDimension = append(mock.calls.GetFilterDimension, callInfo)
	lockMongoDBMockGetFilterDimension.Unlock()
	return mock.GetFilterDimensionFunc(filterID, name)
}

// GetFilterDimensionCalls gets all the calls that were made to GetFilterDimension.
// Check the length with:
//     len(mockedMongoDB.GetFilterDimensionCalls())
func (mock *MongoDBMock) GetFilterDimensionCalls() []struct {
	FilterID string
	Name     string
} {
	var calls []struct {
		FilterID string
		Name     string
	}
	lockMongoDBMockGetFilterDimension.RLock()
	calls = mock.calls.GetFilterDimension
	lockMongoDBMockGetFilterDimension.RUnlock()
	return calls
}

// GetFilterOutput calls GetFilterOutputFunc.
func (mock *MongoDBMock) GetFilterOutput(filterOutputID string) (*models.Filter, error) {
	if mock.GetFilterOutputFunc == nil {
		panic("MongoDBMock.GetFilterOutputFunc: method is nil but MongoDB.GetFilterOutput was just called")
	}
	callInfo := struct {
		FilterOutputID string
	}{
		FilterOutputID: filterOutputID,
	}
	lockMongoDBMockGetFilterOutput.Lock()
	mock.calls.GetFilterOutput = append(mock.calls.GetFilterOutput, callInfo)
	lockMongoDBMockGetFilterOutput.Unlock()
	return mock.GetFilterOutputFunc(filterOutputID)
}

// GetFilterOutputCalls gets all the calls that were made to GetFilterOutput.
// Check the length with:
//     len(mockedMongoDB.GetFilterOutputCalls())
func (mock *MongoDBMock) GetFilterOutputCalls() []struct {
	FilterOutputID string
} {
	var calls []struct {
		FilterOutputID string
	}
	lockMongoDBMockGetFilterOutput.RLock()
	calls = mock.calls.GetFilterOutput
	lockMongoDBMockGetFilterOutput.RUnlock()
	return calls
}

// RemoveFilterDimension calls RemoveFilterDimensionFunc.
func (mock *MongoDBMock) RemoveFilterDimension(filterID string, name string, timestamp bson.MongoTimestamp) error {
	if mock.RemoveFilterDimensionFunc == nil {
		panic("MongoDBMock.RemoveFilterDimensionFunc: method is nil but MongoDB.RemoveFilterDimension was just called")
	}
	callInfo := struct {
		FilterID  string
		Name      string
		Timestamp bson.MongoTimestamp
	}{
		FilterID:  filterID,
		Name:      name,
		Timestamp: timestamp,
	}
	lockMongoDBMockRemoveFilterDimension.Lock()
	mock.calls.RemoveFilterDimension = append(mock.calls.RemoveFilterDimension, callInfo)
	lockMongoDBMockRemoveFilterDimension.Unlock()
	return mock.RemoveFilterDimensionFunc(filterID, name, timestamp)
}

// RemoveFilterDimensionCalls gets all the calls that were made to RemoveFilterDimension.
// Check the length with:
//     len(mockedMongoDB.RemoveFilterDimensionCalls())
func (mock *MongoDBMock) RemoveFilterDimensionCalls() []struct {
	FilterID  string
	Name      string
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		FilterID  string
		Name      string
		Timestamp bson.MongoTimestamp
	}
	lockMongoDBMockRemoveFilterDimension.RLock()
	calls = mock.calls.RemoveFilterDimension
	lockMongoDBMockRemoveFilterDimension.RUnlock()
	return calls
}

// RemoveFilterDimensionOption calls RemoveFilterDimensionOptionFunc.
func (mock *MongoDBMock) RemoveFilterDimensionOption(filterID string, name string, option string, timestamp bson.MongoTimestamp) error {
	if mock.RemoveFilterDimensionOptionFunc == nil {
		panic("MongoDBMock.RemoveFilterDimensionOptionFunc: method is nil but MongoDB.RemoveFilterDimensionOption was just called")
	}
	callInfo := struct {
		FilterID  string
		Name      string
		Option    string
		Timestamp bson.MongoTimestamp
	}{
		FilterID:  filterID,
		Name:      name,
		Option:    option,
		Timestamp: timestamp,
	}
	lockMongoDBMockRemoveFilterDimensionOption.Lock()
	mock.calls.RemoveFilterDimensionOption = append(mock.calls.RemoveFilterDimensionOption, callInfo)
	lockMongoDBMockRemoveFilterDimensionOption.Unlock()
	return mock.RemoveFilterDimensionOptionFunc(filterID, name, option, timestamp)
}

// RemoveFilterDimensionOptionCalls gets all the calls that were made to RemoveFilterDimensionOption.
// Check the length with:
//     len(mockedMongoDB.RemoveFilterDimensionOptionCalls())
func (mock *MongoDBMock) RemoveFilterDimensionOptionCalls() []struct {
	FilterID  string
	Name      string
	Option    string
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		FilterID  string
		Name      string
		Option    string
		Timestamp bson.MongoTimestamp
	}
	lockMongoDBMockRemoveFilterDimensionOption.RLock()
	calls = mock.calls.RemoveFilterDimensionOption
	lockMongoDBMockRemoveFilterDimensionOption.RUnlock()
	return calls
}

// RemoveFilterDimensionOptions calls RemoveFilterDimensionOptionsFunc.
func (mock *MongoDBMock) RemoveFilterDimensionOptions(filterID string, name string, options []string, timestamp bson.MongoTimestamp) error {
	if mock.RemoveFilterDimensionOptionsFunc == nil {
		panic("MongoDBMock.RemoveFilterDimensionOptionsFunc: method is nil but MongoDB.RemoveFilterDimensionOptions was just called")
	}
	callInfo := struct {
		FilterID  string
		Name      string
		Options   []string
		Timestamp bson.MongoTimestamp
	}{
		FilterID:  filterID,
		Name:      name,
		Options:   options,
		Timestamp: timestamp,
	}
	lockMongoDBMockRemoveFilterDimensionOptions.Lock()
	mock.calls.RemoveFilterDimensionOptions = append(mock.calls.RemoveFilterDimensionOptions, callInfo)
	lockMongoDBMockRemoveFilterDimensionOptions.Unlock()
	return mock.RemoveFilterDimensionOptionsFunc(filterID, name, options, timestamp)
}

// RemoveFilterDimensionOptionsCalls gets all the calls that were made to RemoveFilterDimensionOptions.
// Check the length with:
//     len(mockedMongoDB.RemoveFilterDimensionOptionsCalls())
func (mock *MongoDBMock) RemoveFilterDimensionOptionsCalls() []struct {
	FilterID  string
	Name      string
	Options   []string
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		FilterID  string
		Name      string
		Options   []string
		Timestamp bson.MongoTimestamp
	}
	lockMongoDBMockRemoveFilterDimensionOptions.RLock()
	calls = mock.calls.RemoveFilterDimensionOptions
	lockMongoDBMockRemoveFilterDimensionOptions.RUnlock()
	return calls
}

// UpdateFilter calls UpdateFilterFunc.
func (mock *MongoDBMock) UpdateFilter(filter *models.Filter, timestamp bson.MongoTimestamp) error {
	if mock.UpdateFilterFunc == nil {
		panic("MongoDBMock.UpdateFilterFunc: method is nil but MongoDB.UpdateFilter was just called")
	}
	callInfo := struct {
		Filter    *models.Filter
		Timestamp bson.MongoTimestamp
	}{
		Filter:    filter,
		Timestamp: timestamp,
	}
	lockMongoDBMockUpdateFilter.Lock()
	mock.calls.UpdateFilter = append(mock.calls.UpdateFilter, callInfo)
	lockMongoDBMockUpdateFilter.Unlock()
	return mock.UpdateFilterFunc(filter, timestamp)
}

// UpdateFilterCalls gets all the calls that were made to UpdateFilter.
// Check the length with:
//     len(mockedMongoDB.UpdateFilterCalls())
func (mock *MongoDBMock) UpdateFilterCalls() []struct {
	Filter    *models.Filter
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		Filter    *models.Filter
		Timestamp bson.MongoTimestamp
	}
	lockMongoDBMockUpdateFilter.RLock()
	calls = mock.calls.UpdateFilter
	lockMongoDBMockUpdateFilter.RUnlock()
	return calls
}

// UpdateFilterOutput calls UpdateFilterOutputFunc.
func (mock *MongoDBMock) UpdateFilterOutput(filterOutput *models.Filter, timestamp bson.MongoTimestamp) error {
	if mock.UpdateFilterOutputFunc == nil {
		panic("MongoDBMock.UpdateFilterOutputFunc: method is nil but MongoDB.UpdateFilterOutput was just called")
	}
	callInfo := struct {
		FilterOutput *models.Filter
		Timestamp    bson.MongoTimestamp
	}{
		FilterOutput: filterOutput,
		Timestamp:    timestamp,
	}
	lockMongoDBMockUpdateFilterOutput.Lock()
	mock.calls.UpdateFilterOutput = append(mock.calls.UpdateFilterOutput, callInfo)
	lockMongoDBMockUpdateFilterOutput.Unlock()
	return mock.UpdateFilterOutputFunc(filterOutput, timestamp)
}

// UpdateFilterOutputCalls gets all the calls that were made to UpdateFilterOutput.
// Check the length with:
//     len(mockedMongoDB.UpdateFilterOutputCalls())
func (mock *MongoDBMock) UpdateFilterOutputCalls() []struct {
	FilterOutput *models.Filter
	Timestamp    bson.MongoTimestamp
} {
	var calls []struct {
		FilterOutput *models.Filter
		Timestamp    bson.MongoTimestamp
	}
	lockMongoDBMockUpdateFilterOutput.RLock()
	calls = mock.calls.UpdateFilterOutput
	lockMongoDBMockUpdateFilterOutput.RUnlock()
	return calls
}
