// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package observationstoretest

import (
	"github.com/ONSdigital/dp-filter/observation"
	"sync"
)

var (
	lockObservationStoreMockGetCSVRows sync.RWMutex
)

// ObservationStoreMock is a mock implementation of ObservationStore.
//
//     func TestSomethingThatUsesObservationStore(t *testing.T) {
//
//         // make and configure a mocked ObservationStore
//         mockedObservationStore := &ObservationStoreMock{
//             GetCSVRowsFunc: func(in1 *observation.Filter, in2 *int) (observation.CSVRowReader, error) {
// 	               panic("TODO: mock out the GetCSVRows method")
//             },
//         }
//
//         // TODO: use mockedObservationStore in code that requires ObservationStore
//         //       and then make assertions.
//
//     }
type ObservationStoreMock struct {
	// GetCSVRowsFunc mocks the GetCSVRows method.
	GetCSVRowsFunc func(in1 *observation.Filter, in2 *int) (observation.CSVRowReader, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetCSVRows holds details about calls to the GetCSVRows method.
		GetCSVRows []struct {
			// In1 is the in1 argument value.
			In1 *observation.Filter
			// In2 is the in2 argument value.
			In2 *int
		}
	}
}

// GetCSVRows calls GetCSVRowsFunc.
func (mock *ObservationStoreMock) GetCSVRows(in1 *observation.Filter, in2 *int) (observation.CSVRowReader, error) {
	if mock.GetCSVRowsFunc == nil {
		panic("moq: ObservationStoreMock.GetCSVRowsFunc is nil but ObservationStore.GetCSVRows was just called")
	}
	callInfo := struct {
		In1 *observation.Filter
		In2 *int
	}{
		In1: in1,
		In2: in2,
	}
	lockObservationStoreMockGetCSVRows.Lock()
	mock.calls.GetCSVRows = append(mock.calls.GetCSVRows, callInfo)
	lockObservationStoreMockGetCSVRows.Unlock()
	return mock.GetCSVRowsFunc(in1, in2)
}

// GetCSVRowsCalls gets all the calls that were made to GetCSVRows.
// Check the length with:
//     len(mockedObservationStore.GetCSVRowsCalls())
func (mock *ObservationStoreMock) GetCSVRowsCalls() []struct {
	In1 *observation.Filter
	In2 *int
} {
	var calls []struct {
		In1 *observation.Filter
		In2 *int
	}
	lockObservationStoreMockGetCSVRows.RLock()
	calls = mock.calls.GetCSVRows
	lockObservationStoreMockGetCSVRows.RUnlock()
	return calls
}
