// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package datastoretest

import (
	"github.com/ONSdigital/dp-filter-api/models"
	"github.com/gedge/mgo/bson"
	"sync"
)

var (
	lockDataStoreMockAddFilter                   sync.RWMutex
	lockDataStoreMockAddFilterDimension          sync.RWMutex
	lockDataStoreMockAddFilterDimensionOption    sync.RWMutex
	lockDataStoreMockCreateFilterOutput          sync.RWMutex
	lockDataStoreMockGetFilter                   sync.RWMutex
	lockDataStoreMockGetFilterDimension          sync.RWMutex
	lockDataStoreMockGetFilterOutput             sync.RWMutex
	lockDataStoreMockRemoveFilterDimension       sync.RWMutex
	lockDataStoreMockRemoveFilterDimensionOption sync.RWMutex
	lockDataStoreMockUpdateFilter                sync.RWMutex
	lockDataStoreMockUpdateFilterOutput          sync.RWMutex
)

// DataStoreMock is a mock implementation of DataStore.
//
//     func TestSomethingThatUsesDataStore(t *testing.T) {
//
//         // make and configure a mocked DataStore
//         mockedDataStore := &DataStoreMock{
//             AddFilterFunc: func(host string, filter *models.Filter) (*models.Filter, error) {
// 	               panic("TODO: mock out the AddFilter method")
//             },
//             AddFilterDimensionFunc: func(filterID string, name string, options []string, dimensions []models.Dimension, timestamp bson.MongoTimestamp) error {
// 	               panic("TODO: mock out the AddFilterDimension method")
//             },
//             AddFilterDimensionOptionFunc: func(filterID string, name string, option string, timestamp bson.MongoTimestamp) error {
// 	               panic("TODO: mock out the AddFilterDimensionOption method")
//             },
//             CreateFilterOutputFunc: func(filter *models.Filter) error {
// 	               panic("TODO: mock out the CreateFilterOutput method")
//             },
//             GetFilterFunc: func(filterID string) (*models.Filter, error) {
// 	               panic("TODO: mock out the GetFilter method")
//             },
//             GetFilterDimensionFunc: func(filterID string, name string) (*models.Dimension, error) {
// 	               panic("TODO: mock out the GetFilterDimension method")
//             },
//             GetFilterOutputFunc: func(filterOutputID string) (*models.Filter, error) {
// 	               panic("TODO: mock out the GetFilterOutput method")
//             },
//             RemoveFilterDimensionFunc: func(filterID string, name string, timestamp bson.MongoTimestamp) error {
// 	               panic("TODO: mock out the RemoveFilterDimension method")
//             },
//             RemoveFilterDimensionOptionFunc: func(filterID string, name string, option string, timestamp bson.MongoTimestamp) error {
// 	               panic("TODO: mock out the RemoveFilterDimensionOption method")
//             },
//             UpdateFilterFunc: func(filter *models.Filter, timestamp bson.MongoTimestamp) error {
// 	               panic("TODO: mock out the UpdateFilter method")
//             },
//             UpdateFilterOutputFunc: func(filterOutput *models.Filter, timestamp bson.MongoTimestamp) error {
// 	               panic("TODO: mock out the UpdateFilterOutput method")
//             },
//         }
//
//         // TODO: use mockedDataStore in code that requires DataStore
//         //       and then make assertions.
//
//     }
type DataStoreMock struct {
	// AddFilterFunc mocks the AddFilter method.
	AddFilterFunc func(host string, filter *models.Filter) (*models.Filter, error)

	// AddFilterDimensionFunc mocks the AddFilterDimension method.
	AddFilterDimensionFunc func(filterID string, name string, options []string, dimensions []models.Dimension, timestamp bson.MongoTimestamp) error

	// AddFilterDimensionOptionFunc mocks the AddFilterDimensionOption method.
	AddFilterDimensionOptionFunc func(filterID string, name string, option string, timestamp bson.MongoTimestamp) error

	// CreateFilterOutputFunc mocks the CreateFilterOutput method.
	CreateFilterOutputFunc func(filter *models.Filter) error

	// GetFilterFunc mocks the GetFilter method.
	GetFilterFunc func(filterID string) (*models.Filter, error)

	// GetFilterDimensionFunc mocks the GetFilterDimension method.
	GetFilterDimensionFunc func(filterID string, name string) (*models.Dimension, error)

	// GetFilterOutputFunc mocks the GetFilterOutput method.
	GetFilterOutputFunc func(filterOutputID string) (*models.Filter, error)

	// RemoveFilterDimensionFunc mocks the RemoveFilterDimension method.
	RemoveFilterDimensionFunc func(filterID string, name string, timestamp bson.MongoTimestamp) error

	// RemoveFilterDimensionOptionFunc mocks the RemoveFilterDimensionOption method.
	RemoveFilterDimensionOptionFunc func(filterID string, name string, option string, timestamp bson.MongoTimestamp) error

	// UpdateFilterFunc mocks the UpdateFilter method.
	UpdateFilterFunc func(filter *models.Filter, timestamp bson.MongoTimestamp) error

	// UpdateFilterOutputFunc mocks the UpdateFilterOutput method.
	UpdateFilterOutputFunc func(filterOutput *models.Filter, timestamp bson.MongoTimestamp) error

	// calls tracks calls to the methods.
	calls struct {
		// AddFilter holds details about calls to the AddFilter method.
		AddFilter []struct {
			// Host is the host argument value.
			Host string
			// Filter is the filter argument value.
			Filter *models.Filter
		}
		// AddFilterDimension holds details about calls to the AddFilterDimension method.
		AddFilterDimension []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options []string
			// Dimensions is the dimensions argument value.
			Dimensions []models.Dimension
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// AddFilterDimensionOption holds details about calls to the AddFilterDimensionOption method.
		AddFilterDimensionOption []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Option is the option argument value.
			Option string
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// CreateFilterOutput holds details about calls to the CreateFilterOutput method.
		CreateFilterOutput []struct {
			// Filter is the filter argument value.
			Filter *models.Filter
		}
		// GetFilter holds details about calls to the GetFilter method.
		GetFilter []struct {
			// FilterID is the filterID argument value.
			FilterID string
		}
		// GetFilterDimension holds details about calls to the GetFilterDimension method.
		GetFilterDimension []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
		}
		// GetFilterOutput holds details about calls to the GetFilterOutput method.
		GetFilterOutput []struct {
			// FilterOutputID is the filterOutputID argument value.
			FilterOutputID string
		}
		// RemoveFilterDimension holds details about calls to the RemoveFilterDimension method.
		RemoveFilterDimension []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// RemoveFilterDimensionOption holds details about calls to the RemoveFilterDimensionOption method.
		RemoveFilterDimensionOption []struct {
			// FilterID is the filterID argument value.
			FilterID string
			// Name is the name argument value.
			Name string
			// Option is the option argument value.
			Option string
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// UpdateFilter holds details about calls to the UpdateFilter method.
		UpdateFilter []struct {
			// Filter is the filter argument value.
			Filter *models.Filter
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
		// UpdateFilterOutput holds details about calls to the UpdateFilterOutput method.
		UpdateFilterOutput []struct {
			// FilterOutput is the filterOutput argument value.
			FilterOutput *models.Filter
			// Timestamp is the timestamp argument value.
			Timestamp bson.MongoTimestamp
		}
	}
}

// AddFilter calls AddFilterFunc.
func (mock *DataStoreMock) AddFilter(host string, filter *models.Filter) (*models.Filter, error) {
	if mock.AddFilterFunc == nil {
		panic("moq: DataStoreMock.AddFilterFunc is nil but DataStore.AddFilter was just called")
	}
	callInfo := struct {
		Host   string
		Filter *models.Filter
	}{
		Host:   host,
		Filter: filter,
	}
	lockDataStoreMockAddFilter.Lock()
	mock.calls.AddFilter = append(mock.calls.AddFilter, callInfo)
	lockDataStoreMockAddFilter.Unlock()
	return mock.AddFilterFunc(host, filter)
}

// AddFilterCalls gets all the calls that were made to AddFilter.
// Check the length with:
//     len(mockedDataStore.AddFilterCalls())
func (mock *DataStoreMock) AddFilterCalls() []struct {
	Host   string
	Filter *models.Filter
} {
	var calls []struct {
		Host   string
		Filter *models.Filter
	}
	lockDataStoreMockAddFilter.RLock()
	calls = mock.calls.AddFilter
	lockDataStoreMockAddFilter.RUnlock()
	return calls
}

// AddFilterDimension calls AddFilterDimensionFunc.
func (mock *DataStoreMock) AddFilterDimension(filterID string, name string, options []string, dimensions []models.Dimension, timestamp bson.MongoTimestamp) error {
	if mock.AddFilterDimensionFunc == nil {
		panic("moq: DataStoreMock.AddFilterDimensionFunc is nil but DataStore.AddFilterDimension was just called")
	}
	callInfo := struct {
		FilterID   string
		Name       string
		Options    []string
		Dimensions []models.Dimension
		Timestamp  bson.MongoTimestamp
	}{
		FilterID:   filterID,
		Name:       name,
		Options:    options,
		Dimensions: dimensions,
		Timestamp:  timestamp,
	}
	lockDataStoreMockAddFilterDimension.Lock()
	mock.calls.AddFilterDimension = append(mock.calls.AddFilterDimension, callInfo)
	lockDataStoreMockAddFilterDimension.Unlock()
	return mock.AddFilterDimensionFunc(filterID, name, options, dimensions, timestamp)
}

// AddFilterDimensionCalls gets all the calls that were made to AddFilterDimension.
// Check the length with:
//     len(mockedDataStore.AddFilterDimensionCalls())
func (mock *DataStoreMock) AddFilterDimensionCalls() []struct {
	FilterID   string
	Name       string
	Options    []string
	Dimensions []models.Dimension
	Timestamp  bson.MongoTimestamp
} {
	var calls []struct {
		FilterID   string
		Name       string
		Options    []string
		Dimensions []models.Dimension
		Timestamp  bson.MongoTimestamp
	}
	lockDataStoreMockAddFilterDimension.RLock()
	calls = mock.calls.AddFilterDimension
	lockDataStoreMockAddFilterDimension.RUnlock()
	return calls
}

// AddFilterDimensionOption calls AddFilterDimensionOptionFunc.
func (mock *DataStoreMock) AddFilterDimensionOption(filterID string, name string, option string, timestamp bson.MongoTimestamp) error {
	if mock.AddFilterDimensionOptionFunc == nil {
		panic("moq: DataStoreMock.AddFilterDimensionOptionFunc is nil but DataStore.AddFilterDimensionOption was just called")
	}
	callInfo := struct {
		FilterID  string
		Name      string
		Option    string
		Timestamp bson.MongoTimestamp
	}{
		FilterID:  filterID,
		Name:      name,
		Option:    option,
		Timestamp: timestamp,
	}
	lockDataStoreMockAddFilterDimensionOption.Lock()
	mock.calls.AddFilterDimensionOption = append(mock.calls.AddFilterDimensionOption, callInfo)
	lockDataStoreMockAddFilterDimensionOption.Unlock()
	return mock.AddFilterDimensionOptionFunc(filterID, name, option, timestamp)
}

// AddFilterDimensionOptionCalls gets all the calls that were made to AddFilterDimensionOption.
// Check the length with:
//     len(mockedDataStore.AddFilterDimensionOptionCalls())
func (mock *DataStoreMock) AddFilterDimensionOptionCalls() []struct {
	FilterID  string
	Name      string
	Option    string
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		FilterID  string
		Name      string
		Option    string
		Timestamp bson.MongoTimestamp
	}
	lockDataStoreMockAddFilterDimensionOption.RLock()
	calls = mock.calls.AddFilterDimensionOption
	lockDataStoreMockAddFilterDimensionOption.RUnlock()
	return calls
}

// CreateFilterOutput calls CreateFilterOutputFunc.
func (mock *DataStoreMock) CreateFilterOutput(filter *models.Filter) error {
	if mock.CreateFilterOutputFunc == nil {
		panic("moq: DataStoreMock.CreateFilterOutputFunc is nil but DataStore.CreateFilterOutput was just called")
	}
	callInfo := struct {
		Filter *models.Filter
	}{
		Filter: filter,
	}
	lockDataStoreMockCreateFilterOutput.Lock()
	mock.calls.CreateFilterOutput = append(mock.calls.CreateFilterOutput, callInfo)
	lockDataStoreMockCreateFilterOutput.Unlock()
	return mock.CreateFilterOutputFunc(filter)
}

// CreateFilterOutputCalls gets all the calls that were made to CreateFilterOutput.
// Check the length with:
//     len(mockedDataStore.CreateFilterOutputCalls())
func (mock *DataStoreMock) CreateFilterOutputCalls() []struct {
	Filter *models.Filter
} {
	var calls []struct {
		Filter *models.Filter
	}
	lockDataStoreMockCreateFilterOutput.RLock()
	calls = mock.calls.CreateFilterOutput
	lockDataStoreMockCreateFilterOutput.RUnlock()
	return calls
}

// GetFilter calls GetFilterFunc.
func (mock *DataStoreMock) GetFilter(filterID string) (*models.Filter, error) {
	if mock.GetFilterFunc == nil {
		panic("moq: DataStoreMock.GetFilterFunc is nil but DataStore.GetFilter was just called")
	}
	callInfo := struct {
		FilterID string
	}{
		FilterID: filterID,
	}
	lockDataStoreMockGetFilter.Lock()
	mock.calls.GetFilter = append(mock.calls.GetFilter, callInfo)
	lockDataStoreMockGetFilter.Unlock()
	return mock.GetFilterFunc(filterID)
}

// GetFilterCalls gets all the calls that were made to GetFilter.
// Check the length with:
//     len(mockedDataStore.GetFilterCalls())
func (mock *DataStoreMock) GetFilterCalls() []struct {
	FilterID string
} {
	var calls []struct {
		FilterID string
	}
	lockDataStoreMockGetFilter.RLock()
	calls = mock.calls.GetFilter
	lockDataStoreMockGetFilter.RUnlock()
	return calls
}

// GetFilterDimension calls GetFilterDimensionFunc.
func (mock *DataStoreMock) GetFilterDimension(filterID string, name string) (*models.Dimension, error) {
	if mock.GetFilterDimensionFunc == nil {
		panic("moq: DataStoreMock.GetFilterDimensionFunc is nil but DataStore.GetFilterDimension was just called")
	}
	callInfo := struct {
		FilterID string
		Name     string
	}{
		FilterID: filterID,
		Name:     name,
	}
	lockDataStoreMockGetFilterDimension.Lock()
	mock.calls.GetFilterDimension = append(mock.calls.GetFilterDimension, callInfo)
	lockDataStoreMockGetFilterDimension.Unlock()
	return mock.GetFilterDimensionFunc(filterID, name)
}

// GetFilterDimensionCalls gets all the calls that were made to GetFilterDimension.
// Check the length with:
//     len(mockedDataStore.GetFilterDimensionCalls())
func (mock *DataStoreMock) GetFilterDimensionCalls() []struct {
	FilterID string
	Name     string
} {
	var calls []struct {
		FilterID string
		Name     string
	}
	lockDataStoreMockGetFilterDimension.RLock()
	calls = mock.calls.GetFilterDimension
	lockDataStoreMockGetFilterDimension.RUnlock()
	return calls
}

// GetFilterOutput calls GetFilterOutputFunc.
func (mock *DataStoreMock) GetFilterOutput(filterOutputID string) (*models.Filter, error) {
	if mock.GetFilterOutputFunc == nil {
		panic("moq: DataStoreMock.GetFilterOutputFunc is nil but DataStore.GetFilterOutput was just called")
	}
	callInfo := struct {
		FilterOutputID string
	}{
		FilterOutputID: filterOutputID,
	}
	lockDataStoreMockGetFilterOutput.Lock()
	mock.calls.GetFilterOutput = append(mock.calls.GetFilterOutput, callInfo)
	lockDataStoreMockGetFilterOutput.Unlock()
	return mock.GetFilterOutputFunc(filterOutputID)
}

// GetFilterOutputCalls gets all the calls that were made to GetFilterOutput.
// Check the length with:
//     len(mockedDataStore.GetFilterOutputCalls())
func (mock *DataStoreMock) GetFilterOutputCalls() []struct {
	FilterOutputID string
} {
	var calls []struct {
		FilterOutputID string
	}
	lockDataStoreMockGetFilterOutput.RLock()
	calls = mock.calls.GetFilterOutput
	lockDataStoreMockGetFilterOutput.RUnlock()
	return calls
}

// RemoveFilterDimension calls RemoveFilterDimensionFunc.
func (mock *DataStoreMock) RemoveFilterDimension(filterID string, name string, timestamp bson.MongoTimestamp) error {
	if mock.RemoveFilterDimensionFunc == nil {
		panic("moq: DataStoreMock.RemoveFilterDimensionFunc is nil but DataStore.RemoveFilterDimension was just called")
	}
	callInfo := struct {
		FilterID  string
		Name      string
		Timestamp bson.MongoTimestamp
	}{
		FilterID:  filterID,
		Name:      name,
		Timestamp: timestamp,
	}
	lockDataStoreMockRemoveFilterDimension.Lock()
	mock.calls.RemoveFilterDimension = append(mock.calls.RemoveFilterDimension, callInfo)
	lockDataStoreMockRemoveFilterDimension.Unlock()
	return mock.RemoveFilterDimensionFunc(filterID, name, timestamp)
}

// RemoveFilterDimensionCalls gets all the calls that were made to RemoveFilterDimension.
// Check the length with:
//     len(mockedDataStore.RemoveFilterDimensionCalls())
func (mock *DataStoreMock) RemoveFilterDimensionCalls() []struct {
	FilterID  string
	Name      string
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		FilterID  string
		Name      string
		Timestamp bson.MongoTimestamp
	}
	lockDataStoreMockRemoveFilterDimension.RLock()
	calls = mock.calls.RemoveFilterDimension
	lockDataStoreMockRemoveFilterDimension.RUnlock()
	return calls
}

// RemoveFilterDimensionOption calls RemoveFilterDimensionOptionFunc.
func (mock *DataStoreMock) RemoveFilterDimensionOption(filterID string, name string, option string, timestamp bson.MongoTimestamp) error {
	if mock.RemoveFilterDimensionOptionFunc == nil {
		panic("moq: DataStoreMock.RemoveFilterDimensionOptionFunc is nil but DataStore.RemoveFilterDimensionOption was just called")
	}
	callInfo := struct {
		FilterID  string
		Name      string
		Option    string
		Timestamp bson.MongoTimestamp
	}{
		FilterID:  filterID,
		Name:      name,
		Option:    option,
		Timestamp: timestamp,
	}
	lockDataStoreMockRemoveFilterDimensionOption.Lock()
	mock.calls.RemoveFilterDimensionOption = append(mock.calls.RemoveFilterDimensionOption, callInfo)
	lockDataStoreMockRemoveFilterDimensionOption.Unlock()
	return mock.RemoveFilterDimensionOptionFunc(filterID, name, option, timestamp)
}

// RemoveFilterDimensionOptionCalls gets all the calls that were made to RemoveFilterDimensionOption.
// Check the length with:
//     len(mockedDataStore.RemoveFilterDimensionOptionCalls())
func (mock *DataStoreMock) RemoveFilterDimensionOptionCalls() []struct {
	FilterID  string
	Name      string
	Option    string
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		FilterID  string
		Name      string
		Option    string
		Timestamp bson.MongoTimestamp
	}
	lockDataStoreMockRemoveFilterDimensionOption.RLock()
	calls = mock.calls.RemoveFilterDimensionOption
	lockDataStoreMockRemoveFilterDimensionOption.RUnlock()
	return calls
}

// UpdateFilter calls UpdateFilterFunc.
func (mock *DataStoreMock) UpdateFilter(filter *models.Filter, timestamp bson.MongoTimestamp) error {
	if mock.UpdateFilterFunc == nil {
		panic("moq: DataStoreMock.UpdateFilterFunc is nil but DataStore.UpdateFilter was just called")
	}
	callInfo := struct {
		Filter    *models.Filter
		Timestamp bson.MongoTimestamp
	}{
		Filter:    filter,
		Timestamp: timestamp,
	}
	lockDataStoreMockUpdateFilter.Lock()
	mock.calls.UpdateFilter = append(mock.calls.UpdateFilter, callInfo)
	lockDataStoreMockUpdateFilter.Unlock()
	return mock.UpdateFilterFunc(filter, timestamp)
}

// UpdateFilterCalls gets all the calls that were made to UpdateFilter.
// Check the length with:
//     len(mockedDataStore.UpdateFilterCalls())
func (mock *DataStoreMock) UpdateFilterCalls() []struct {
	Filter    *models.Filter
	Timestamp bson.MongoTimestamp
} {
	var calls []struct {
		Filter    *models.Filter
		Timestamp bson.MongoTimestamp
	}
	lockDataStoreMockUpdateFilter.RLock()
	calls = mock.calls.UpdateFilter
	lockDataStoreMockUpdateFilter.RUnlock()
	return calls
}

// UpdateFilterOutput calls UpdateFilterOutputFunc.
func (mock *DataStoreMock) UpdateFilterOutput(filterOutput *models.Filter, timestamp bson.MongoTimestamp) error {
	if mock.UpdateFilterOutputFunc == nil {
		panic("moq: DataStoreMock.UpdateFilterOutputFunc is nil but DataStore.UpdateFilterOutput was just called")
	}
	callInfo := struct {
		FilterOutput *models.Filter
		Timestamp    bson.MongoTimestamp
	}{
		FilterOutput: filterOutput,
		Timestamp:    timestamp,
	}
	lockDataStoreMockUpdateFilterOutput.Lock()
	mock.calls.UpdateFilterOutput = append(mock.calls.UpdateFilterOutput, callInfo)
	lockDataStoreMockUpdateFilterOutput.Unlock()
	return mock.UpdateFilterOutputFunc(filterOutput, timestamp)
}

// UpdateFilterOutputCalls gets all the calls that were made to UpdateFilterOutput.
// Check the length with:
//     len(mockedDataStore.UpdateFilterOutputCalls())
func (mock *DataStoreMock) UpdateFilterOutputCalls() []struct {
	FilterOutput *models.Filter
	Timestamp    bson.MongoTimestamp
} {
	var calls []struct {
		FilterOutput *models.Filter
		Timestamp    bson.MongoTimestamp
	}
	lockDataStoreMockUpdateFilterOutput.RLock()
	calls = mock.calls.UpdateFilterOutput
	lockDataStoreMockUpdateFilterOutput.RUnlock()
	return calls
}
