---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.4

inputs:
  - name: dp-filter-api

outputs:
  - name: build

run:
  path: dp-filter-api/ci/scripts/build.sh
